---
title: C assignment example
description: An example of grading script using the testcase tool and valgrind
instructions: |
    <h4>The problem</h4>
    <p>
        In this exercise you must implement a linked list, that 
        prints the cars that are given in from a file namen cars.txt.
    </p>
    <h4>Assessment</h4>
    <p>
      This assignment has two tests. The first one is running the assignment in valgrind to check if it has issues such as memory leaks.
      Second test is a basic I/O test that compares the output of the assignment to the expected one.
    </p>

view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: assignment.c

container:
  image: apluslms/grade-c:latest
  mount: exercises/c_test
  cmd: /exercise/run.sh
